@startuml
'https://plantuml.com/class-diagram

class Website{
- String sitename
- String author
+ generateSiteFolder
+ generateJSFolder
+ generateCSSFolder
+ generateIndexFile
}

class App{
+ promptString
+ promptBoolean
+ createWebsite
+ printOutput
}

@enduml